version: 2

project_name: pvmt

before:
  hooks:
    - go mod tidy
    - make wasm
    - go run ./cmd/gendocs

builds:
  - id: pvmt
    main: ./cmd/pvmt
    binary: pvmt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/jcrussell/solvent-streets/internal/build.Version={{.Version}}
      - -X github.com/jcrussell/solvent-streets/internal/build.Commit={{.Commit}}
      - -X github.com/jcrussell/solvent-streets/internal/build.Date={{.Date}}

archives:
  - id: pvmt
    ids:
      - pvmt
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - completions/*
      - manpages/*.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - id: archives
    artifacts: archive
    cmd: syft
    args:
      - "scan"
      - "${artifact}"
      - "--output"
      - "cyclonedx-json=${document}"
    documents:
      - "${artifact}.sbom.cdx.json"

signs:
  - cmd: cosign
    artifacts: all
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999

release:
  github:
    owner: jcrussell
    name: solvent-streets
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
