// Test harness for internal/export/templates/app.js.
//
// app.js is a plain top-level browser script (NOT an IIFE and NOT a module):
// it is embedded verbatim into the Go binary via go:embed and shipped as-is,
// so it must stay loadable by a bare <script src>. This harness therefore
// never imports it — it reads the file and evaluates it inside a jsdom window,
// which is also why every top-level function it declares becomes a property of
// that window and is directly reachable from a test.
//
// The DOM is NOT hand-written here. index.html.tmpl is a Go template, and the
// city <option> elements that drive selectCity are generated by it, so a
// hand-rolled or regex-stripped fixture would silently lack exactly the
// elements the interesting tests need. A Go test (js_harness_test.go) renders
// the real template and points PVMT_FIXTURE_DIR at the result.
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP_JS = join(HERE, '..', 'app.js');

export function fixtureDir() {
  const dir = process.env.PVMT_FIXTURE_DIR;
  if (!dir) {
    throw new Error(
      'PVMT_FIXTURE_DIR is unset. These tests render index.html from the Go ' +
      'template; run them via `make test-js`, not `node --test` directly.');
  }
  return dir;
}

// installStubs provides the browser APIs app.js reaches for at evaluation time.
// Each entry here is load-bearing: without it app.js throws before any test
// gets to run.
function installStubs(win, { data, simulate }) {
  // MapLibre GL, not Leaflet. app.js constructs `new maplibregl.Map(...)` at
  // top level and later swaps sources and layers on it, so this needs real
  // behaviour rather than a no-op: updateHexGrid reads back the source it just
  // added, and loadCityData tears layers down and rebuilds them.
  const sources = new Map();
  const layers = new Map();
  const handlers = new Map();
  win.maplibregl = {
    Map: class {
      constructor() {
        this.__sources = sources;
        this.__layers = layers;
        this.__handlers = handlers;
      }
      on(ev, a, b) { (handlers.get(ev) || handlers.set(ev, []).get(ev)).push(b || a); return this; }
      off() { return this; }
      once(ev, fn) { return this.on(ev, fn); }
      addSource(id, spec) { sources.set(id, { ...spec, setData(d) { this.data = d; } }); }
      getSource(id) { return sources.get(id); }
      removeSource(id) { sources.delete(id); }
      addLayer(spec) { layers.set(spec.id, spec); }
      getLayer(id) { return layers.get(id); }
      removeLayer(id) { layers.delete(id); }
      setPaintProperty() {}
      setLayoutProperty() {}
      setFilter() {}
      fitBounds() {}
      flyTo() {}
      easeTo() {}
      jumpTo() {}
      resize() {}
      remove() {}
      getCanvas() { return { style: {} }; }
      getContainer() { return win.document.createElement('div'); }
      unproject() { return { lng: 0, lat: 0 }; }
      project() { return { x: 0, y: 0 }; }
      queryRenderedFeatures() { return []; }
      addControl() { return this; }
      getZoom() { return 10; }
      setStyle() { return this; }
      get dragPan() { return { enable() {}, disable() {} }; }
      get scrollZoom() { return { enable() {}, disable() {} }; }
      get boxZoom() { return { enable() {}, disable() {} }; }
    },
    NavigationControl: class {},
    Popup: class {
      setLngLat() { return this; }
      setHTML() { return this; }
      addTo() { return this; }
      remove() { return this; }
    },
    LngLatBounds: class {
      extend() { return this; }
      isEmpty() { return false; }
    },
  };

  // Chart.js. Instances are recorded so a test can read what was plotted
  // without a canvas.
  win.__charts = [];
  win.Chart = class {
    constructor(ctx, cfg) {
      this.ctx = ctx;
      this.config = cfg;
      this.data = cfg && cfg.data;
      this.options = cfg && cfg.options;
      win.__charts.push(this);
    }
    update() {}
    destroy() {}
    resize() {}
  };
  // app.js calls Chart.register(...) at top level to install plugins.
  win.Chart.register = () => {};
  win.Chart.defaults = { font: {}, plugins: { legend: { labels: {} }, tooltip: {} }, scale: { grid: {} } };

  // jsdom throws "not implemented" from getContext. app.js calls it
  // unconditionally at ten sites, all immediately before `new Chart(...)`,
  // so a token object is enough — the Chart stub above ignores it.
  win.HTMLCanvasElement.prototype.getContext = () => ({ canvas: null });

  // The WASM bridge. app.js calls window.simulateForecast(JSON.stringify(in))
  // and expects a JSON string back. Every call is recorded so a test can count
  // simulations — note each runCustomScenario produces TWO of these (the year-1
  // baseline inside getControlValues, then the result).
  win.__simCalls = [];
  win.simulateForecast = (json) => {
    const input = JSON.parse(json);
    win.__simCalls.push(input);
    return JSON.stringify(simulate(input));
  };

  // Static-site fetch over the fixture data. Anything not in `data` 404s, which
  // is a case app.js is meant to survive (loadJSON returns null).
  win.fetch = async (url) => {
    const key = String(url).split('?')[0].replace(/^\.?\//, '');
    const hit = Object.keys(data).find((k) => key.endsWith(k));
    if (!hit) {
      return { ok: false, status: 404, json: async () => { throw new Error('404'); } };
    }
    return { ok: true, status: 200, json: async () => JSON.parse(JSON.stringify(data[hit])) };
  };
}

// defaultSimulate returns a plausible ScenarioResult for the given input:
// PCI decays, backlog grows, and the shape matches what the Go bridge emits.
// Tests that care about specific numbers pass their own.
export function defaultSimulate(input) {
  const years = [];
  let pci = input.initial_pci ?? 70;
  let backlog = 0;
  const n = input.years ?? 20;
  for (let y = 1; y <= n; y++) {
    pci = Math.max(0, pci - 2);
    const need = (input.area ?? 1e6) * 0.5;
    const spend = input.annual_budget ?? 0;
    backlog += Math.max(0, need - spend);
    years.push({
      year: y, pci, area: input.area ?? 1e6,
      annual_need: need, annual_spend: spend,
      deferred_backlog: backlog, cost_tier: 'rehab',
    });
  }
  return {
    scenario: { name: 'custom', strategy: 0 },
    years,
    final_cohorts: (input.cohorts ?? []).map((c) => ({
      classification: c.classification ?? 'residential',
      end_pci: pci, area: c.area ?? 1e5, decay_rate: c.decay_rate ?? 0.04,
      total_spend: 1e6, total_deficit: 1e5,
    })),
  };
}

// load builds a window from the rendered index.html, installs stubs, evaluates
// app.js in it, and returns the window plus a few helpers.
//
// `data` maps a data-file suffix (e.g. 'scenarios.json') to a parsed object;
// the fetch stub matches by suffix so both single-city ('data/x.json') and
// multi-city ('cities/<slug>/x.json') prefixes resolve.
export function load({ data = {}, simulate = defaultSimulate, url = 'https://example.test/index.html' } = {}) {
  const html = readFileSync(join(fixtureDir(), 'index.html'), 'utf8');
  const dom = new JSDOM(html, {
    url,
    runScripts: 'dangerously',   // executes the inline PVMT_CONFIG + theme_boot
    resources: undefined,        // external <script src> are NOT fetched
    pretendToBeVisual: true,
  });
  const win = dom.window;

  // jsdom has localStorage, but tests need it empty and isolated per load.
  win.localStorage.clear();
  installStubs(win, { data, simulate });

  // Run app.js as a real classic script, exactly as <script src> would —
  // NOT via win.eval(). eval evaluates in its own declarative environment, so
  // every top-level `let`/`const` in app.js (hexDataByScope, UNIT_SYSTEM,
  // wasmReady, ...) would be created there and discarded, leaving them
  // invisible to `get` below. Appending a <script> puts those bindings in the
  // window's global lexical environment, where they belong.
  const el = win.document.createElement('script');
  el.textContent = readFileSync(APP_JS, 'utf8');
  win.document.body.appendChild(el);

  return {
    dom,
    win,
    doc: win.document,
    $: (sel) => win.document.querySelector(sel),
    $$: (sel) => Array.from(win.document.querySelectorAll(sel)),
    // get evaluates an expression in app.js's own scope. Needed because
    // top-level `let`/`const` bindings live in the global LEXICAL environment
    // and are not properties of the window — so `win.hexDataByScope` is
    // undefined even though the binding exists. Function declarations DO become
    // window properties, which is why `win.loadCityData()` works directly.
    get: (expr) => win.eval(expr),
    // simCalls counts window.simulateForecast invocations, i.e. actual WASM
    // simulations — not runCustomScenario calls, which are two each.
    simCalls: () => win.__simCalls.length,
    resetSimCalls: () => { win.__simCalls.length = 0; },
    // flush lets pending microtasks (loadJSON chains) settle.
    flush: async (n = 6) => { for (let i = 0; i < n; i++) await new Promise((r) => setTimeout(r, 0)); },
  };
}
