// Executing coverage for the Materials tab, which had none — which is how
// solvent-streets-q48z.11 shipped: concrete sidewalk area billed as hot-mix
// asphalt in the mix/binder/oil headlines.
//
// The fixture is generated by the real exporter (js_harness_test.go) over the
// golden fixture city, whose cohorts include sidewalks, so asphalt_area_share
// is genuinely below 1 here and these assertions test real netting rather than
// a no-op multiply by 1.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { load } from './harness.mjs';
import { fullData, seedJSON, readFixture } from './fixtures.mjs';

// ready boots a window and renders the Materials tab.
async function ready(data = fullData) {
  const h = load({ data });
  await h.flush();
  await h.win.loadMaterials();
  await h.flush();
  return h;
}

// seedWithoutShare is the pre-fix seed: same fixture, both share keys removed.
// readFixture re-parses from disk each call, so mutating it is safe.
function seedWithoutShare() {
  const seed = readFixture('forecast_seed.json');
  delete seed.asphalt_area_share;
  delete seed.city_asphalt_area_share;
  return seed;
}

// seedWithShare pins both share keys to a given value, for the degenerate ends
// of the range the fixture city cannot reach on its own.
function seedWithShare(share) {
  const seed = readFixture('forecast_seed.json');
  seed.asphalt_area_share = share;
  seed.city_asphalt_area_share = share;
  return seed;
}

// Parses a headline like "3,197 tons/yr", "1.2K tons/yr" or "830 bbl/yr" back
// to a number. Charts are stubbed out under jsdom, so the headlines are the
// readable surface — and they come off the same materialSeries the charts use.
// The thousands separators are load-bearing to strip: leaving them in truncates
// "3,197" to 3, which made a real 7.6% effect measure as no effect at all.
function headline(win, id) {
  const text = win.document.getElementById(id).textContent;
  const m = text.match(/^([\d,.]+)\s*([KM]?)/);
  assert.ok(m, `could not parse headline #${id}: ${JSON.stringify(text)}`);
  const n = parseFloat(m[1].replace(/,/g, ''));
  assert.ok(Number.isFinite(n), `headline #${id} is not a number: ${JSON.stringify(text)}`);
  return n * (m[2] === 'K' ? 1e3 : m[2] === 'M' ? 1e6 : 1);
}

// The fixture must actually exercise the netting branch. If the exporter ever
// stops emitting the key, or the fixture city loses its sidewalk cohorts, every
// other test in this file silently degrades to asserting share === 1.
test('the fixture seed carries an asphalt share below 1', () => {
  const seed = seedJSON;
  assert.equal(typeof seed.asphalt_area_share, 'number',
    'asphalt_area_share missing from the exporter-generated seed');
  assert.ok(seed.asphalt_area_share > 0 && seed.asphalt_area_share < 1,
    `asphalt_area_share = ${seed.asphalt_area_share}; the fixture city must have ` +
    'sidewalk cohorts for the netting tests below to mean anything');
  assert.equal(typeof seed.city_asphalt_area_share, 'number',
    'city_asphalt_area_share missing from the exporter-generated seed');
});

// The bug: material intensities are flexible-pavement-only (forecast/material.go
// says outright that sidewalks are concrete), but scenario.years[].area sums
// every resource. Multiplying the two attributes crude-oil-equivalent barrels to
// concrete panels that consume zero bitumen.
test('the mix/binder/oil headlines net concrete sidewalk area out', async () => {
  const { win } = await ready();
  const seed = seedJSON;
  // The tab defaults to the city scope when the seed has city_paved.
  const share = seed.city_paved ? seed.city_asphalt_area_share : seed.asphalt_area_share;

  const netted = {
    mix: headline(win, 'hl-mix'),
    binder: headline(win, 'hl-binder'),
    oil: headline(win, 'hl-oil'),
  };
  for (const [name, value] of Object.entries(netted)) {
    assert.ok(value > 0, `#hl-${name} rendered ${value}; the tab did not compute anything`);
  }

  // Re-render with the share removed — the pre-fix behavior — and confirm every
  // headline was larger by exactly 1/share. Asserting the ratio rather than
  // "it got smaller" is what pins the arithmetic.
  const h2 = await ready({ ...fullData, 'forecast_seed.json': seedWithoutShare() });
  const gross = {
    mix: headline(h2.win, 'hl-mix'),
    binder: headline(h2.win, 'hl-binder'),
    oil: headline(h2.win, 'hl-oil'),
  };
  for (const name of Object.keys(netted)) {
    // Headlines are rounded for display, so compare with a tolerance rather
    // than exactly; the effect (7-11% here) is far larger than the rounding.
    const ratio = gross[name] / netted[name];
    assert.ok(Math.abs(ratio - 1 / share) < 0.02,
      `#hl-${name}: un-netted/netted = ${ratio}, want ~${1 / share} (1/asphalt share)`);
    assert.ok(gross[name] > netted[name],
      `#hl-${name} did not shrink when the sidewalk area was netted out`);
  }
});

// A seed exported before the field existed must render exactly as it used to,
// not blank out. `undefined` reaching the multiply as 0 would zero the tab.
test('an older seed without the share renders unchanged, not blank', async () => {
  const { win } = await ready({ ...fullData, 'forecast_seed.json': seedWithoutShare() });
  assert.ok(headline(win, 'hl-mix') > 0, '#hl-mix blanked out on a seed with no asphalt share');
  assert.ok(headline(win, 'hl-oil') > 0, '#hl-oil blanked out on a seed with no asphalt share');
});

// The note explains why these figures do not reconcile with the network area on
// the other tabs. Without it a reader sees two different "network areas" and no
// reason for the gap.
test('the note says concrete is excluded when the share is below 1', async () => {
  const { win } = await ready();
  const note = win.document.getElementById('materials-note').textContent;
  assert.match(note, /Concrete sidewalks are excluded/,
    'the materials note does not mention the excluded concrete area');

  const h2 = await ready({ ...fullData, 'forecast_seed.json': seedWithoutShare() });
  assert.doesNotMatch(h2.win.document.getElementById('materials-note').textContent,
    /Concrete sidewalks are excluded/,
    'the exclusion note appeared for a seed that does not net anything out');
});

// solvent-streets-ujji: the note is shown for any share < 1, but the percentage
// it prints used to be rounded, so both ends of the range contradicted the
// sentence they sat in. A share in [0.995, 1) printed "cover the 100% of network
// area" while claiming sidewalks were excluded; a legitimate 0 (a concrete-only
// network) printed "cover the 0%".
test('the note never prints 0% or 100% while claiming an exclusion', async () => {
  for (const share of [0.999, 0.9951, 0.004, 0]) {
    const { win } = await ready({ ...fullData, 'forecast_seed.json': seedWithShare(share) });
    const note = win.document.getElementById('materials-note').textContent;
    assert.match(note, /Concrete sidewalks are excluded/,
      `the exclusion note vanished at share ${share}`);
    assert.doesNotMatch(note, /cover the 100% of network area/,
      `share ${share} claimed full coverage while excluding a nonzero area`);
    assert.doesNotMatch(note, /cover the 0% of network area/,
      `share ${share} claimed zero coverage in a note about what IS covered`);
  }
});

// Sanity: the tab renders its charts off the real exporter scenarios, so a
// scenario-name or key drift shows up here the way it did on Financials.
test('the Materials tab renders its charts from real exporter data', async () => {
  const { $$ } = await ready();
  const titles = $$('#materials-charts h3').map((h) => h.textContent);
  assert.ok(titles.length > 0, 'the Materials tab rendered no charts');
});
