package export

// DataFileNames is the single source of truth for the per-city data files a
// publish-ready export writes under data/ (single-city) or cities/<slug>/data/
// (multi-city). The exporter writes these at the call sites in export.go
// (writeCityData / exportScenariosForCity); some are written conditionally
// there (boundary only when a boundary exists, the forecast trio only when
// forecasts are present), but for a fully-computed, publish-ready city all of
// them are expected — `pvmt check-site` treats a missing one as a failure.
//
// Sorted for deterministic comparison against an on-disk directory listing.
var DataFileNames = []string{
	"boundary.geojson",
	"forecast.json",
	"forecast_seed.json",
	"hex-cost-summary.json",
	"hexgrid.geojson",
	"meta.json",
	"scenarios.json",
}

// EmbeddedWasmAssets returns the shared WASM assets embedded into this binary,
// keyed by their on-disk filename at the site root. `pvmt check-site` uses this
// to compare sha256 against the copies written into a built tree, so a site
// generated by an older binary is flagged as stale. The returned slices are the
// embedded backing arrays — callers must not mutate them.
func EmbeddedWasmAssets() map[string][]byte {
	return map[string][]byte{
		"forecast.wasm": forecastWasm,
		"wasm_exec.js":  wasmExecJS,
	}
}
