package export

import (
	"context"
	"encoding/json"
	"html/template"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/jcrussell/solvent-streets/internal/config"
	"github.com/jcrussell/solvent-streets/internal/db"
	"github.com/jcrussell/solvent-streets/internal/db/dbtest"
	"github.com/jcrussell/solvent-streets/internal/forecast"
)

// TestJS drives the executing JavaScript tests for
// internal/export/templates/app.js (solvent-streets-azdu / e2xk).
//
// It lives on the Go side rather than being a bare `node --test` because the
// DOM those tests need comes from index.html.tmpl, which is a Go template. The
// city <option> elements selectCity reads (opt.dataset.bbox) are generated by
// it, so a hand-written or regex-stripped HTML fixture would silently lack
// exactly the elements the interesting tests exercise — and would then drift
// from the template with nothing to notice. Rendering the real template here
// means a template change that breaks the client fails this test.
//
// Skips (rather than fails) when node or node_modules are missing, so
// `go test ./...` still works on a machine with no JS toolchain. CI installs
// them; see the test-js make target.
func TestJS(t *testing.T) {
	if testing.Short() {
		t.Skip("short mode")
	}
	root := repoRoot(t)
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH; run `make test-js`")
	}
	if _, err := os.Stat(filepath.Join(root, "node_modules", "jsdom")); err != nil {
		t.Skip("node_modules/jsdom missing; run `npm ci` or `make test-js`")
	}

	dir := t.TempDir()
	writeJSFixtureTree(t, dir)

	// Glob form, not the bare directory: `node --test <dir>` resolves the path
	// as a module and fails with ENOENT.
	cmd := exec.Command("node", "--test", "internal/export/templates/__tests__/*.test.mjs")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "PVMT_FIXTURE_DIR="+dir)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("node --test failed: %v\n%s", err, out)
	}
	t.Logf("node --test output:\n%s", out)
}

// repoRoot walks up from this source file to the module root.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("go.mod not found above " + file)
		}
		dir = parent
	}
}

// jsFixtureSnapshotID is the snapshot the fixture meta.json is dated from.
// Non-zero on purpose: snapshotDate falls back to time.Now() for id <= 0, and a
// fixture that changes daily is a fixture that can drift under a test.
const jsFixtureSnapshotID = 1

// jsFixtureBoundary is the city polygon BuildMeta derives bbox, center, area and
// pct_paved from. Roughly the alpha-ca box the rendered index.html carries, so
// the fetched meta.json and the city <option> in the DOM describe one city.
const jsFixtureBoundary = `{"type":"Polygon","coordinates":[[[-122.3,37.7],[-122.2,37.7],[-122.2,37.8],[-122.3,37.8],[-122.3,37.7]]]}`

// jsFixtureForecastConfig is goldenForecastConfig with two deliberate changes:
// a 20-year horizon (what a real site ships) and the canonical worst-tier label
// "reconstruction". The golden's "reconstruct" does not match
// forecast.DefaultMaterialTiers, so reusing it verbatim would silently drive the
// Materials tab down MaterialTierFor's fallback path instead of a label match.
//
// The tier PRICES are deliberately not restated here: relabelling a clone keeps
// this config following the golden's, where copying the literal would let the
// two drift apart with nothing to notice — the failure this whole fixture
// arrangement exists to rule out.
func jsFixtureForecastConfig(t *testing.T) config.ForecastConfig {
	t.Helper()
	fc := goldenForecastConfig()
	fc.Years = 20
	fc.CostTiers = slices.Clone(fc.CostTiers)
	worst := len(fc.CostTiers) - 1
	if fc.CostTiers[worst].Label != "reconstruct" {
		t.Fatalf("goldenForecastConfig's worst tier is now %q; check which tier needs the canonical label",
			fc.CostTiers[worst].Label)
	}
	fc.CostTiers[worst].Label = "reconstruction"
	return fc
}

// jsFixtureEntry is goldenFixtureEntry plus the two reads BuildMeta needs that
// the golden tests do not: a boundary polygon and a dated snapshot.
func jsFixtureEntry(t *testing.T) CityEntry {
	t.Helper()
	entry := goldenFixtureEntry(t)
	store, ok := entry.Store.(*dbtest.MockStore)
	if !ok {
		t.Fatalf("goldenFixtureEntry store is %T, not *dbtest.MockStore", entry.Store)
	}
	store.GetBoundaryFunc = func(context.Context) (string, error) { return jsFixtureBoundary, nil }
	store.ListSnapshotsFunc = func(context.Context) ([]db.Snapshot, error) {
		return []db.Snapshot{{ID: jsFixtureSnapshotID, ComputedAt: time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)}}, nil
	}
	// Matches a city option in the rendered index.html, so meta.project_name and
	// the DOM describe the same place.
	entry.City.Name = "Alpha, CA"
	entry.Slug = "alpha-ca"
	return entry
}

// writeJSFixtureTree writes everything the JS specs read: index.html rendered
// from the real Go template, and the four data files the fetch stub serves.
//
// The data is NOT hand-written, for the same reason the DOM is not: it is built
// by the real exporter entry points (BuildMeta, BuildForecastsForCity,
// BuildScenariosData, BuildForecastSeed) over the deterministic DB-free fixture
// the golden tests already use, then rounded through the same emission helpers
// export.go writes with. A hand-rolled fixture drifts from the Go json tags
// silently — which is exactly what happened (solvent-streets-q48z.8): the seed
// said `area` where Go emits `total_area`, the scenarios were named
// `do-nothing`/`maintain` where the exporter emits `baseline`/`fund-*`, and
// meta put total_area at the top level instead of inside stats[]. Three of the
// four Financials charts never rendered under test, and the suite was green.
func writeJSFixtureTree(t *testing.T, dir string) {
	t.Helper()
	ctx := context.Background()
	fc := jsFixtureForecastConfig(t)
	entry := jsFixtureEntry(t)

	seed, err := BuildForecastSeed(ctx, &fc, entry.Store)
	if err != nil {
		t.Fatalf("build forecast seed: %v", err)
	}
	writeJSFixtureSite(t, dir, seed)

	meta, err := BuildMeta(ctx, entry, jsFixtureSnapshotID)
	if err != nil {
		t.Fatalf("build meta: %v", err)
	}
	forecasts, err := BuildForecastsForCity(ctx, entry, &fc, ConvertCostTiers(&fc))
	if err != nil {
		t.Fatalf("build forecasts: %v", err)
	}
	scenarios, err := BuildScenariosData(ctx, entry, &fc)
	if err != nil {
		t.Fatalf("build scenarios: %v", err)
	}

	// Tripwires. Each of these is something the JS specs assert on; if the Go
	// side stops producing it, fail HERE with a clear cause rather than leaving
	// a spec to pass vacuously over an empty chart list.
	if len(meta.Stats) == 0 {
		t.Fatal("fixture meta.json has no stats[]; the stats-panel specs would test nothing")
	}
	if len(forecasts) == 0 {
		t.Fatal("fixture forecast.json is empty; the Financials specs would test nothing")
	}
	assertFundingScenarios(t, scenarios)

	writeFixtureJSON(t, dir, "meta.json", meta)
	writeFixtureJSON(t, dir, "forecast.json", RoundForecastsForEmission(forecasts))
	writeFixtureJSON(t, dir, "scenarios.json", RoundScenariosForEmission(scenarios))
	if err := os.WriteFile(filepath.Join(dir, "forecast_seed.json"), []byte(seed), 0o644); err != nil {
		t.Fatalf("write forecast_seed.json: %v", err)
	}
}

// assertFundingScenarios pins the scenario names app.js filters on
// (FUNDING_SCENARIO_NAMES). Renaming one on the Go side drops a chart from the
// Financials tab; without this the JS specs would just see fewer charts and,
// before q48z.8, asserted nothing about how many.
func assertFundingScenarios(t *testing.T, scenarios map[string]any) {
	t.Helper()
	want := []string{"baseline", "fund-25pct", "fund-50pct", "fund-100pct"}
	for _, scope := range []string{"city", "bbox"} {
		results, ok := scenarios[scope].([]forecast.ScenarioResult)
		if !ok {
			t.Fatalf("fixture scenarios.json has no %q scope (%T)", scope, scenarios[scope])
		}
		got := make([]string, 0, len(results))
		for _, r := range results {
			got = append(got, r.Scenario.Name)
		}
		if !slices.Equal(got, want) {
			t.Fatalf("fixture scenarios.json %s scope = %v, want %v", scope, got, want)
		}
	}
}

func writeFixtureJSON(t *testing.T, dir, name string, v any) {
	t.Helper()
	data, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal %s: %v", name, err)
	}
	if err := os.WriteFile(filepath.Join(dir, name), data, 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

// writeJSFixtureSite renders index.html from the real template into dir, with
// the same forecast seed the fetched forecast_seed.json carries — the inline
// PVMT_CONFIG.forecastSeed and the per-city fetch must agree, or a spec that
// reads one is describing the other.
func writeJSFixtureSite(t *testing.T, dir string, seed template.JS) {
	t.Helper()

	cities := []CityInfo{
		{Slug: "alpha-ca", Name: "Alpha, CA", BBox: [4]float64{-122.3, 37.7, -122.2, 37.8}, CenterLon: -122.25, CenterLat: 37.75, Tags: []string{"Metro"}},
		{Slug: "beta-ca", Name: "Beta, CA", BBox: [4]float64{-121.8, 37.6, -121.7, 37.7}, CenterLon: -121.75, CenterLat: 37.65, Tags: []string{"Metro", "Top 50"}},
		{Slug: "gamma-ca", Name: "Gamma, CA", BBox: [4]float64{-121.3, 38.5, -121.2, 38.6}, CenterLon: -121.25, CenterLat: 38.55},
	}

	td := TemplateData{
		MetaJSON:      MetaJSON{ProjectName: "Harness"},
		ForecastSeed:  seed,
		LayerColors:   ResourceColorsJS(),
		UnitSystem:    "imperial",
		Cities:        cities,
		CitiesByTag:   GroupCitiesByTag(cities),
		GeneratedDate: "2026-01-01",
		BuildVersion:  "test",
	}

	index, err := renderPage(ParseIndexTemplate, td)
	if err != nil {
		t.Fatalf("render index: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "index.html"), index, 0o644); err != nil {
		t.Fatalf("write index.html: %v", err)
	}

	// Tripwire: if the template stops emitting city options, every selectCity
	// test below would pass vacuously against an empty selector.
	if !strings.Contains(string(index), `data-slug="beta-ca"`) && !strings.Contains(string(index), `value="beta-ca"`) {
		t.Fatal("rendered index.html has no city options; the JS fixtures would test nothing")
	}
}

// TestJSFixturesAreNotEmbedded guards a quiet packaging hazard: template.go's
// directive is `//go:embed templates`, i.e. the WHOLE directory. The __tests__
// subdirectory escapes it only because go:embed skips names beginning with `_`
// or `.`. Rename it to `tests/` or `testdata/` and every fixture, harness and
// spec would be compiled into every pvmt binary, silently, with nothing failing.
func TestJSFixturesAreNotEmbedded(t *testing.T) {
	err := fs.WalkDir(templatesFS, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if strings.Contains(p, "__tests__") || strings.HasSuffix(p, ".test.mjs") || strings.HasSuffix(p, ".mjs") {
			t.Errorf("JS test asset embedded into the binary: %s — the test directory must stay underscore-prefixed", p)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk embedded templates: %v", err)
	}
}
