package export

import (
	"encoding/json"
	"html/template"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// TestJS drives the executing JavaScript tests for
// internal/export/templates/app.js (solvent-streets-azdu / e2xk).
//
// It lives on the Go side rather than being a bare `node --test` because the
// DOM those tests need comes from index.html.tmpl, which is a Go template. The
// city <option> elements selectCity reads (opt.dataset.bbox) are generated by
// it, so a hand-written or regex-stripped HTML fixture would silently lack
// exactly the elements the interesting tests exercise — and would then drift
// from the template with nothing to notice. Rendering the real template here
// means a template change that breaks the client fails this test.
//
// Skips (rather than fails) when node or node_modules are missing, so
// `go test ./...` still works on a machine with no JS toolchain. CI installs
// them; see the test-js make target.
func TestJS(t *testing.T) {
	if testing.Short() {
		t.Skip("short mode")
	}
	root := repoRoot(t)
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not on PATH; run `make test-js`")
	}
	if _, err := os.Stat(filepath.Join(root, "node_modules", "jsdom")); err != nil {
		t.Skip("node_modules/jsdom missing; run `npm ci` or `make test-js`")
	}

	dir := t.TempDir()
	writeJSFixtureSite(t, dir)

	// Glob form, not the bare directory: `node --test <dir>` resolves the path
	// as a module and fails with ENOENT.
	cmd := exec.Command("node", "--test", "internal/export/templates/__tests__/*.test.mjs")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "PVMT_FIXTURE_DIR="+dir)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("node --test failed: %v\n%s", err, out)
	}
	t.Logf("node --test output:\n%s", out)
}

// repoRoot walks up from this source file to the module root.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("go.mod not found above " + file)
		}
		dir = parent
	}
}

// writeJSFixtureSite renders index.html from the real template into dir. Only
// the HTML is written: the JS tests serve every data file through a stubbed
// fetch, so no ingest, compute or export run is needed.
func writeJSFixtureSite(t *testing.T, dir string) {
	t.Helper()

	cities := []CityInfo{
		{Slug: "alpha-ca", Name: "Alpha, CA", BBox: [4]float64{-122.3, 37.7, -122.2, 37.8}, CenterLon: -122.25, CenterLat: 37.75, Tags: []string{"Metro"}},
		{Slug: "beta-ca", Name: "Beta, CA", BBox: [4]float64{-121.8, 37.6, -121.7, 37.7}, CenterLon: -121.75, CenterLat: 37.65, Tags: []string{"Metro", "Top 50"}},
		{Slug: "gamma-ca", Name: "Gamma, CA", BBox: [4]float64{-121.3, 38.5, -121.2, 38.6}, CenterLon: -121.25, CenterLat: 38.55},
	}

	seed, err := json.Marshal(map[string]any{
		"initial_pci":           68,
		"decay_rate":            0.04,
		"growth_rate":           0,
		"years":                 20,
		"treatment_cycle_years": 12,
		"area":                  3_300_000,
		"cost_tiers": []map[string]any{
			{"min_pci": 70, "max_pci": 101, "cost_per_sqm": 5, "label": "preventive"},
			{"min_pci": 40, "max_pci": 70, "cost_per_sqm": 50, "label": "rehab"},
			{"min_pci": 0, "max_pci": 40, "cost_per_sqm": 150, "label": "reconstruction"},
		},
		"cohorts": []map[string]any{
			{"classification": "residential", "area": 2_000_000, "decay_rate": 0.045, "initial_pci": 68},
			{"classification": "primary", "area": 1_300_000, "decay_rate": 0.03, "initial_pci": 68},
		},
	})
	if err != nil {
		t.Fatalf("marshal seed: %v", err)
	}

	td := TemplateData{
		MetaJSON:      MetaJSON{ProjectName: "Harness"},
		ForecastSeed:  template.JS(seed),
		LayerColors:   ResourceColorsJS(),
		UnitSystem:    "imperial",
		Cities:        cities,
		CitiesByTag:   GroupCitiesByTag(cities),
		GeneratedDate: "2026-01-01",
		BuildVersion:  "test",
	}

	index, err := renderPage(ParseIndexTemplate, td)
	if err != nil {
		t.Fatalf("render index: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "index.html"), index, 0o644); err != nil {
		t.Fatalf("write index.html: %v", err)
	}

	// Tripwire: if the template stops emitting city options, every selectCity
	// test below would pass vacuously against an empty selector.
	if !strings.Contains(string(index), `data-slug="beta-ca"`) && !strings.Contains(string(index), `value="beta-ca"`) {
		t.Fatal("rendered index.html has no city options; the JS fixtures would test nothing")
	}
}

// TestJSFixturesAreNotEmbedded guards a quiet packaging hazard: template.go's
// directive is `//go:embed templates`, i.e. the WHOLE directory. The __tests__
// subdirectory escapes it only because go:embed skips names beginning with `_`
// or `.`. Rename it to `tests/` or `testdata/` and every fixture, harness and
// spec would be compiled into every pvmt binary, silently, with nothing failing.
func TestJSFixturesAreNotEmbedded(t *testing.T) {
	err := fs.WalkDir(templatesFS, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if strings.Contains(p, "__tests__") || strings.HasSuffix(p, ".test.mjs") || strings.HasSuffix(p, ".mjs") {
			t.Errorf("JS test asset embedded into the binary: %s — the test directory must stay underscore-prefixed", p)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk embedded templates: %v", err)
	}
}
